go:
    version: 1.14
repository:
    path: github.com/slesinger/apigee-exporter
build:
    flags: -mod=vendor -a -tags vap
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20200523-15:04:05"}}
tarball:
    files:
        - LICENSE
        - NOTICE
